[profile.default]
src = "src"
out = "out"
libs = ["lib"]

test = "test"
cache_path = "cache"

solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
evm_version = "paris"

fs_permissions = [{ access = "read", path = "./" }]

[fuzz]
runs = 256

# remappings = [
#     '@openzeppelin/=lib/openzeppelin-contracts/contracts/',
#     'forge-std/=lib/forge-std/src/'
# ]

[rpc_endpoints]
hyperevm_testnet = "https://rpcs.chain.link/hyperevm/testnet"

